# Book settings
title: Active Learning Technologies
author: Firas Moosvi
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

# Execution settings
execute:
  execute_notebooks         : 'off'

# Information about where the book exists on the web
repository:
  url                       : https://github.com/firasm/active-learning-technologies  # Online location of your book
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org
  thebelab                  : true