# Book settings
title: Active Learning Technologies
author: Firas Moosvi
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"
  thebelab                  : true