name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install npm and build
      run: |
        npm install
        npm run build

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .

   # Push to server
    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-avz"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: "_build/html"
        TARGET: ${{ secrets.REMOTE_TARGET }}
      run: |
        mkdir ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/gh_actions_key
        chmod 600 ~/.ssh/gh_actions_key
        rsync -avzr --delete -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ${SOURCE} ${REMOTE_USER}@${REMOTE_HOST}:${TARGET}
