name: build and deploy build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build webpack
        env:
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          local_dir: "_build/html"
          remote_dir: ${{ secrets.REMOTE_TARGET }}
        run: |
          mkdir ~/.ssh
          echo "this is a test" > ~/test.txt
          echo "$remote_key" > ~/.ssh/gh_actions_key
          chmod 600 ~/.ssh/gh_actions_key
          rsync -avzr --delete ./test.txt ${remote_user}@${remote_host}:${remote_dir}
